### ISSUE TITLE
Confusing "missing import" warning

### ISSUE THREAD

**Issue by Turbo87** [ember-cli/babel-plugin-ember-modules-api-polyfill#15]
```
SyntaxError: mweb/helpers/invoke.js: rsvp does not have a Promise import
  2 | import { isArray as isEmberArray } from '@ember/array';
  3 | import { tryInvoke } from '@ember/utils';
> 4 | import { Promise } from 'rsvp';
    | ^
  5 |
  6 | export function invoke([methodName, ...args]) {
  7 |   let obj = args.pop();
```

https://github.com/ember-cli/babel-plugin-ember-modules-api-polyfill/blob/v1.4.2/src/index.js#L92

I think this should say "export", not "import", right?

**Comment by Gorzas** [comment]
Also, I've found a similar problem when importing `hash` from `rsvp`:

```
SyntaxError: neuro-frontend/routes/crm/users/index.js: rsvp does not have a hash import
  3 | import { inject } from '@ember/service';
  4 | import Route from '@ember/routing/route';
> 5 | import { hash } from 'rsvp';
    | ^
  6 | 
  7 | export default Route.extend({
```

Should we create another bug about the imports from RSVP?

**Comment by Turbo87** [comment]
@Gorzas which version of `ember-rfc176-data` do you have?

**Comment by Gorzas** [comment]
@Turbo87 v0.2.4, but updating it to version 0.2.6 fixes the problem. I didn't know I have to install `ember-rfc176-data` first :(

**Comment by Turbo87** [comment]
@Gorzas you don't need to, but if you use a lockfile and lock that subdependency to an older version you obviously don't get any bugfixes in that project anymore, and that particular bug that you have was fixed in that dependency.

**Comment by Gorzas** [comment]
Thanks @Turbo87, sorry for the offtopic but I've finally fixed the problem :). I did the following steps:
- Install `babel-plugin-ember-modules-api-polyfill` using *yarn* (by default, it installed `ember-rfc176-data@0.2.4` instead the last one, I don't know why)
- Install `ember-rfc176-data@0.2.6` with *yarn* (it wasn't working because dedupe library)
- Remove `yarn.lock`, but I think I could achieve the same by modifying the version in the `yarn.lock` file
- Install again with `yarn install`
